# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField(verbose_name='章节编号')),
                ('chapter_order', models.CharField(max_length=30, verbose_name='章节序号')),
                ('title', models.CharField(max_length=30, verbose_name='章节名')),
                ('content', models.TextField(verbose_name='正文')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='书名')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('desc', models.CharField(max_length=3000, verbose_name='简介')),
                ('yisou_id', models.PositiveIntegerField(verbose_name='宜搜ID')),
                ('latest_chapter', models.CharField(max_length=30, verbose_name='最新章节')),
                ('latest_chapter_id', models.CharField(max_length=30, verbose_name='最新章节ID')),
                ('last_update_timestamp', models.DateTimeField(verbose_name='更新时间')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resource', models.CharField(max_length=30, verbose_name='来源网站')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novel', verbose_name='书名'),
        ),
    ]
