# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='create_timestamp',
        ),
    ]
