# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20160405_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='站点名称')),
                ('tag', models.CharField(max_length=30, verbose_name='正文tag类型')),
                ('attr_type', models.CharField(max_length=30, verbose_name='定位属性类型')),
                ('attr_type_name', models.CharField(max_length=30, verbose_name='定位属性名称')),
                ('coding', models.CharField(max_length=30, verbose_name='编码')),
            ],
            options={
                'verbose_name_plural': '来源站点',
                'verbose_name': '来源站点',
            },
        ),
    ]
