# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160330_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='block',
            new_name='block_name',
        ),
    ]
