# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bBlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bblock',
            options={'verbose_name': '版块', 'verbose_name_plural': '版块'},
        ),
        migrations.AlterField(
            model_name='bblock',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bblock',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='版块描述'),
        ),
        migrations.AlterField(
            model_name='bblock',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='bblock',
            name='name',
            field=models.CharField(max_length=30, verbose_name='版块名称'),
        ),
    ]
